name: ci
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Smoke import
        run: |
          python - << 'PY'
          import importlib
          m = importlib.import_module("dataset_search_mcp.server")
          assert hasattr(m, "main")
          print("OK: import + entrypoint")
          PY
